name: Node.js CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    rebuild-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: '13.x'
            - run: npm ci
            - name: Building
              run: npx tsc
            - name: Check updates to documents
              run: npm run doc
            - uses: stefanzweifel/git-auto-commit-action@v4.1.1
              with:
                  commit_message: 'chore(docs): update documents'
                  branch: ${{ github.head_ref }}
                  file_pattern: '**/*.md'
                  commit_user_name: GitHub Actions
                  commit_user_email: actions@github.com
                  commit_author: GitHub Actions <actions@github.com>
